[package]
name = "bb"
version = "0.1.0"
authors = ["scott-linder <scott.b.linder@wmich.edu>"]

[dependencies]
mysql = "0.15.0"
iron = "0.1.20"
hyper = "*"
router = "0.0.10"
urlencoded = "0.2.0"
horrorshow = "0.5.2"
time = "0.1"
